### ISSUE TITLE
Helper only works with full names in chat

### ISSUE THREAD

**Issue by Spectral-Fires** [Infiziert90/DeathRoll#1]
I was testing this last night to try to use it for my venue and was noticing that the plugin just wasn't registering dice rolls at all for any of the game modes. Upon further testing this morning I've noticed that if you have your Name Display Type set to anything but Full Name, the plugin simply won't pull rolls from the log into the system.

Unsure if this is a bug or simply a limitation on how the information can be pulled, but worth a mention.

**Comment by Infiziert90** [comment]
Sounds like a bug, I will look into it :)

**Comment by Infiziert90** [comment]
Thanks for the report.
Found the bug and fixed it in the last update, committing it to the repos now :3
