### ISSUE TITLE
No "Draw Both On Start" Bug

### ISSUE THREAD

**Issue by SonyUSA** [Infiziert90/DeathRoll#11]
If you do not have "Draw Both On Start" selected for Blackjack mode, it bugs after rolling the first card for every player and will Auto-Draw the rest of the cards instead of allowing the dealer to /dice for the rest. This may also require "Dealer Draws All Cards" to be selected.

**Comment by SonyUSA** [comment]
Actually, it draws 2 additional cards for every player instead of just 1 more

**Comment by ECEstal** [comment]
Having the same issue. Any idea what the cause is?

**Comment by SonyUSA** [comment]
> Having the same issue. Any idea what the cause is?

I haven't had time to look, I've been beating my backlog of games and haven't touched FFXIV lately, I'm sure myself or Infi will get around to looking at it once Dawntrail comes around lol

**Comment by ECEstal** [comment]
Haha; fair enough. I'll fork it and if I find the issue I'll send it to ya guys.
