### ISSUE TITLE
Unable to install through dulamud. Says to contact the developer

### ISSUE THREAD

**Issue by Monkeraii** [Infiziert90/DeathRoll#13]
Hello, I've been itching to try out this but I have been unable to install. Am I doing something wrong

**Comment by Infiziert90** [comment]
If you have discord, please join the deathroll discord thread on the dalamud discord or add me `@infi`

If that isn't possible would I need your dalamud.log file posted here :)

**Comment by Monkeraii** [comment]
where is the logfile located is it the output.txt? i added you on discord

**Comment by Monkeraii** [comment]
https://pastebin.com/pzgPzRwJ this is my dulamud.txt, says stuff about your plugin throwing errors, im assuming this is what you need
