### ISSUE TITLE
Player Order

### ISSUE THREAD

**Issue by PrinceMew** [Infiziert90/DeathRoll#14]
I don't think I could technically call this an issue since there's nothing wrong with the plugin, but the update that changed the order players got cards unfortunately broke all my macros for blackjack. It's definitely clearer for players to see their hand, but I enjoyed dealing cards out 1 by 1 like in a real game of blackjack, so I'm wondering if that could be added back in as an option. If not, I'll suck it up and redo all my macros.

**Comment by Infiziert90** [comment]
I didn't update that in quite some time, and one of the options should do exactly that.... Mmm

**Comment by PrinceMew** [comment]
Yeah, I hadn't used the plugin in quite some time, but when I was trying to show someone my macros, I was having a lot of trouble. Cards would draw themselves after the first one, and while the draw both on start option gets around that, I preferred one at a time.

**Comment by PrinceMew** [comment]
Recorded it happening if that helps at all
[blackjack bug.zip](https://github.com/Infiziert90/DeathRoll/files/15299360/blackjack.bug.zip)
