### ISSUE TITLE
Allowing the dealer to draw cards for players.

### ISSUE THREAD

**Issue by Lean1275** [Infiziert90/DeathRoll#3]
Is it possible to implement a feature to let the dealer use /dice or /random for other players since people can mess up or not understanding it?
I think it would make the blackjack feature more viable to use!

**Comment by Infiziert90** [comment]
Will be added with the next update :)

**Comment by Infiziert90** [comment]
Hi,

Sorry that everything got a bit delayed.
With one of the next updates will this feature come as a button.

**Comment by SonyUSA** [comment]
> Is it possible to implement a feature to let the dealer use /dice or /random for other players since people can mess up or not understanding it? I think it would make the blackjack feature more viable to use!

Hi! I just wrote some really cursed code to allow this, if you want to try my fork and test it out!
