### ISSUE TITLE
Only recording own rolls

### ISSUE THREAD

**Issue by Petra105** [Infiziert90/DeathRoll#5]
For some reason the plugin is only catching my rolls and not those of those around me or even those of people in my party. Running in Venue mode.

**Comment by Infiziert90** [comment]
Tried to replicate but sadly nothing on my side, works just fine.

I will try a bit more the next days, but currently no idea what could have happend.

**Comment by Infiziert90** [comment]
@Kylis HI, there is a new update coming for the plugin.
After its release could you try and get that bug to happen again, while running it with the debug option on?

If you get it to happen, please share your dalamud log in the DeathRoll Forum on the XIVLauncher & Dalamud Discord, or here on github

**Comment by Petra105** [comment]
Where is the log saved?

**Comment by Infiziert90** [comment]
"%appdata%"/XIVlauncher"

**Comment by Petra105** [comment]
Just the dalamud.log or what?

**Comment by Infiziert90** [comment]
Yep

**Comment by DogeTwo** [comment]
it seems doesn't work here, nothing happen when me and my friend roll.

**Comment by DogeTwo** [comment]
and，how to use Regex to find who rolled the biggest ,or the minnest?

**Comment by Infiziert90** [comment]
> it seems doesn't work here, nothing happen when me and my friend roll.

Can you share your log with debug enabled?

And there is a sort in the option in the venue Mode

**Comment by DogeTwo** [comment]
[dalamud.log](https://github.com/Infiziert90/DeathRoll/files/11365454/dalamud.log)
I guess u mean this thing. hope it's correct one.
（提出中文交流申请）

**Comment by Infiziert90** [comment]
> [dalamud.log](https://github.com/Infiziert90/DeathRoll/files/11365454/dalamud.log) I guess u mean this thing. hope it's correct one. （提出中文交流申请）

Going by the logs i think you are playing on CN and that isn't supported with the global plugin version
But there should be a CN version of this plugin by a dev from CN

**Comment by DogeTwo** [comment]
it does. But it's not working ethier.

**Comment by Infiziert90** [comment]
Please ask the dev to update it :)

**Comment by Infiziert90** [comment]
Closing it as the original User didn't respond anymore, but most likely it was CN issue
