### ISSUE TITLE
Blackjack settings / issues

### ISSUE THREAD

**Issue by Benedictum** [Infiziert90/DeathRoll#7]
Couple things with blackjack feature:

1.) when a player gets 21 via hits, it still counts as a blackjack, it should only count blackjacks if its the initial hand

2.) would like a feature/setting to set the blackjack multiplier, if the venue doesnt offer 2.5x bet on natural blackjacks. Just a box with the multiplier and hand setting it would be great.

**Comment by Infiziert90** [comment]
> 1.) when a player gets 21 via hits, it still counts as a blackjack, it should only count blackjacks if its the initial hand

There is actually different rules how 21 is counted, the ones i found for some casinos was the hit 21 whenever is blackjack :)

> 2.) would like a feature/setting to set the blackjack multiplier, if the venue doesnt offer 2.5x bet on natural blackjacks. Just a box with the multiplier and hand setting it would be great.

Can do that in one of the future updates

**Comment by Benedictum** [comment]
Would it be possible to make a toggle for nat blackjack to only be initial two cards then, vs any 21?

**Comment by Infiziert90** [comment]
1) Option in f74bef2
2) Coming soon
